### ISSUE TITLE
Redis Manifest with Sentinel Job

### ISSUE THREAD

**Issue by ghost** [hybris/redis-boshrelease#1]
Hi,

Does this release support sentinel feature of redis. If yes, could you please provide the sample manifest with sentinel Job sections.

Thanks,
Guru.

**Comment by maksd** [comment]
Hi @GuruprakashS, 

we do, see the sentinel job folder for more details.

Manifest example:

``` YAML
[...]
jobs:
  - name: redis-masters
    instances: 1
    templates:
      - name: redis
        release: redis
      - name: sentinel
        release: redis
    resource_pool: redis-small
    networks:
      - name: default
        static_ips:
            - 10.0.0.1
    properties:
      sentinel:
        masters:
           - 'redis1 10.0.0.1 6379'

  - name: redis-slaves
    templates:
      - name: redis
        release: redis
      - name: sentinel
        release: redis
    instances: 2
    resource_pool: redis-small
    networks:
      - name: default
        static_ips:
            - 10.0.0.2
            - 10.0.0.3
    properties:
      redis:
         master: 10.0.0.1
      sentinel:
        masters:
           - 'redis1 10.0.0.1 6379'
[...]
```
